name: 03 - Execução Pós Deploy

on:
  push:
    branches:
      - main

jobs:
  post-deploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes pós deploy
        run: npm test

      - name: Armazenar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-pos-deploy
          path: |
            mochawesome-report/